// داده نمونه املاک — این آرایه را می‌توانید بعداً با پاسخ یک API واقعی جایگزین کنید
const PROPERTY_LISTINGS = [
  {
    "id": 1,
    "title": "پنت‌هاوس مدرن کارگر",
    "dealType": "rent",
    "propertyType": "penthouse",
    "neighborhood": "کارگر",
    "city": "لاهیجان",
    "area": 75,
    "bedrooms": 1,
    "parking": 1,
    "amenities": [
      "pool",
      "storage",
      "parking",
      "rooftop",
      "gym"
    ],
    "daysAgo": 1,
    "featured": false,
    "image": "assets/img/property-1.svg",
    "rentDeposit": 902000000,
    "rentMonthly": 34000000,
    "price": 34000000
  },
  {
    "id": 2,
    "title": "ویلای باغی گلستان",
    "dealType": "rent",
    "propertyType": "villa",
    "neighborhood": "گلستان",
    "city": "لاهیجان",
    "area": 230,
    "bedrooms": 4,
    "parking": 0,
    "amenities": [
      "parking",
      "security",
      "storage",
      "gym",
      "pool"
    ],
    "daysAgo": 4,
    "featured": false,
    "image": "assets/img/property-2.svg",
    "rentDeposit": 1629000000,
    "rentMonthly": 75300000,
    "price": 75300000
  },
  {
    "id": 3,
    "title": "آپارتمان لاکچری بهشتی",
    "dealType": "mortgage",
    "propertyType": "apartment",
    "neighborhood": "بهشتی",
    "city": "لاهیجان",
    "area": 90,
    "bedrooms": 2,
    "parking": 2,
    "amenities": [
      "rooftop",
      "pool",
      "storage",
      "parking"
    ],
    "daysAgo": 10,
    "featured": false,
    "image": "assets/img/property-3.svg",
    "price": 3800000000
  },
  {
    "id": 4,
    "title": "مغازه خط اول بهشتی",
    "dealType": "rent",
    "propertyType": "commercial",
    "neighborhood": "بهشتی",
    "city": "لاهیجان",
    "area": 35,
    "bedrooms": 0,
    "parking": 2,
    "amenities": [
      "storage",
      "balcony",
      "gym"
    ],
    "daysAgo": 30,
    "featured": false,
    "image": "assets/img/property-4.svg",
    "rentDeposit": 536000000,
    "rentMonthly": 29000000,
    "price": 29000000
  },
  {
    "id": 5,
    "title": "زمین مسکونی ساحلی",
    "dealType": "rent",
    "propertyType": "land",
    "neighborhood": "ساحلی",
    "city": "لاهیجان",
    "area": 400,
    "bedrooms": 0,
    "parking": 0,
    "amenities": [],
    "daysAgo": 6,
    "featured": true,
    "image": "assets/img/property-5.svg",
    "rentDeposit": 7802000000,
    "rentMonthly": 239900000,
    "price": 239900000
  },
  {
    "id": 6,
    "title": "آپارتمان لاکچری سیاهکل‌روبرو",
    "dealType": "rent",
    "propertyType": "apartment",
    "neighborhood": "سیاهکل‌روبرو",
    "city": "لاهیجان",
    "area": 180,
    "bedrooms": 3,
    "parking": 3,
    "amenities": [
      "storage",
      "rooftop",
      "parking",
      "pool",
      "gym"
    ],
    "daysAgo": 14,
    "featured": false,
    "image": "assets/img/property-6.svg",
    "rentDeposit": 2881000000,
    "rentMonthly": 93100000,
    "price": 93100000
  },
  {
    "id": 7,
    "title": "آپارتمان دوبلکس دیلمان",
    "dealType": "sale",
    "propertyType": "apartment",
    "neighborhood": "دیلمان",
    "city": "لاهیجان",
    "area": 420,
    "bedrooms": 4,
    "parking": 0,
    "amenities": [
      "storage",
      "pool"
    ],
    "daysAgo": 14,
    "featured": false,
    "image": "assets/img/property-7.svg",
    "price": 32120000000
  },
  {
    "id": 8,
    "title": "ویلای لوکس چمخاله",
    "dealType": "rent",
    "propertyType": "villa",
    "neighborhood": "چمخاله",
    "city": "لاهیجان",
    "area": 200,
    "bedrooms": 3,
    "parking": 2,
    "amenities": [
      "elevator",
      "pool",
      "gym",
      "rooftop"
    ],
    "daysAgo": 30,
    "featured": false,
    "image": "assets/img/property-8.svg",
    "rentDeposit": 2847000000,
    "rentMonthly": 79100000,
    "price": 79100000
  },
  {
    "id": 9,
    "title": "ویلای باغی رودبنه",
    "dealType": "sale",
    "propertyType": "villa",
    "neighborhood": "رودبنه",
    "city": "لاهیجان",
    "area": 75,
    "bedrooms": 1,
    "parking": 3,
    "amenities": [
      "storage",
      "security",
      "elevator",
      "rooftop"
    ],
    "daysAgo": 25,
    "featured": false,
    "image": "assets/img/property-9.svg",
    "price": 6590000000
  },
  {
    "id": 10,
    "title": "ویلای دوبلکس استخر",
    "dealType": "rent",
    "propertyType": "villa",
    "neighborhood": "استخر",
    "city": "لاهیجان",
    "area": 230,
    "bedrooms": 4,
    "parking": 2,
    "amenities": [
      "pool",
      "balcony"
    ],
    "daysAgo": 1,
    "featured": false,
    "image": "assets/img/property-10.svg",
    "rentDeposit": 1788000000,
    "rentMonthly": 67400000,
    "price": 67400000
  },
  {
    "id": 11,
    "title": "آپارتمان لاکچری ساحلی",
    "dealType": "sale",
    "propertyType": "apartment",
    "neighborhood": "ساحلی",
    "city": "لاهیجان",
    "area": 260,
    "bedrooms": 4,
    "parking": 0,
    "amenities": [
      "rooftop",
      "gym"
    ],
    "daysAgo": 30,
    "featured": false,
    "image": "assets/img/property-11.svg",
    "price": 16720000000
  },
  {
    "id": 12,
    "title": "مغازه تجاری آستانه‌اشرفیه",
    "dealType": "mortgage",
    "propertyType": "commercial",
    "neighborhood": "آستانه‌اشرفیه",
    "city": "لاهیجان",
    "area": 35,
    "bedrooms": 0,
    "parking": 1,
    "amenities": [
      "balcony",
      "security",
      "pool",
      "parking",
      "storage"
    ],
    "daysAgo": 10,
    "featured": false,
    "image": "assets/img/property-12.svg",
    "price": 2435000000
  },
  {
    "id": 13,
    "title": "دفتر کار اداری ساحلی",
    "dealType": "sale",
    "propertyType": "office",
    "neighborhood": "ساحلی",
    "city": "لاهیجان",
    "area": 45,
    "bedrooms": 0,
    "parking": 0,
    "amenities": [
      "balcony",
      "elevator",
      "gym"
    ],
    "daysAgo": 0,
    "featured": false,
    "image": "assets/img/property-1.svg",
    "price": 5290000000
  },
  {
    "id": 14,
    "title": "پنت‌هاوس لوکس امام خمینی",
    "dealType": "sale",
    "propertyType": "penthouse",
    "neighborhood": "امام خمینی",
    "city": "لاهیجان",
    "area": 120,
    "bedrooms": 2,
    "parking": 1,
    "amenities": [
      "balcony",
      "security",
      "parking",
      "gym",
      "rooftop"
    ],
    "daysAgo": 21,
    "featured": false,
    "image": "assets/img/property-2.svg",
    "price": 14710000000
  },
  {
    "id": 15,
    "title": "ویلای دوبلکس نیما",
    "dealType": "sale",
    "propertyType": "villa",
    "neighborhood": "نیما",
    "city": "لاهیجان",
    "area": 180,
    "bedrooms": 3,
    "parking": 1,
    "amenities": [
      "gym",
      "balcony",
      "pool",
      "elevator",
      "security"
    ],
    "daysAgo": 12,
    "featured": false,
    "image": "assets/img/property-3.svg",
    "price": 8830000000
  },
  {
    "id": 16,
    "title": "مغازه تجاری ساحلی",
    "dealType": "sale",
    "propertyType": "commercial",
    "neighborhood": "ساحلی",
    "city": "لاهیجان",
    "area": 80,
    "bedrooms": 0,
    "parking": 2,
    "amenities": [
      "gym",
      "parking",
      "storage"
    ],
    "daysAgo": 5,
    "featured": false,
    "image": "assets/img/property-4.svg",
    "price": 12970000000
  },
  {
    "id": 17,
    "title": "آپارتمان نوساز کریمی",
    "dealType": "rent",
    "propertyType": "apartment",
    "neighborhood": "کریمی",
    "city": "لاهیجان",
    "area": 230,
    "bedrooms": 4,
    "parking": 0,
    "amenities": [
      "elevator",
      "rooftop"
    ],
    "daysAgo": 3,
    "featured": false,
    "image": "assets/img/property-5.svg",
    "rentDeposit": 2556000000,
    "rentMonthly": 128800000,
    "price": 128800000
  },
  {
    "id": 18,
    "title": "ویلای مدرن لاکانی",
    "dealType": "sale",
    "propertyType": "villa",
    "neighborhood": "لاکانی",
    "city": "لاهیجان",
    "area": 180,
    "bedrooms": 3,
    "parking": 1,
    "amenities": [
      "security",
      "balcony",
      "pool",
      "rooftop",
      "gym"
    ],
    "daysAgo": 4,
    "featured": false,
    "image": "assets/img/property-6.svg",
    "price": 9970000000
  },
  {
    "id": 19,
    "title": "پنت‌هاوس لوکس خرمشهر",
    "dealType": "sale",
    "propertyType": "penthouse",
    "neighborhood": "خرمشهر",
    "city": "لاهیجان",
    "area": 160,
    "bedrooms": 3,
    "parking": 0,
    "amenities": [
      "rooftop",
      "security"
    ],
    "daysAgo": 3,
    "featured": true,
    "image": "assets/img/property-7.svg",
    "price": 25810000000
  },
  {
    "id": 20,
    "title": "آپارتمان بازسازی‌شده بهشتی",
    "dealType": "mortgage",
    "propertyType": "apartment",
    "neighborhood": "بهشتی",
    "city": "لاهیجان",
    "area": 90,
    "bedrooms": 2,
    "parking": 2,
    "amenities": [
      "balcony",
      "rooftop"
    ],
    "daysAgo": 5,
    "featured": false,
    "image": "assets/img/property-8.svg",
    "price": 2291000000
  },
  {
    "id": 21,
    "title": "ویلای مدرن رودبنه",
    "dealType": "rent",
    "propertyType": "villa",
    "neighborhood": "رودبنه",
    "city": "لاهیجان",
    "area": 260,
    "bedrooms": 4,
    "parking": 2,
    "amenities": [
      "security",
      "parking",
      "pool",
      "storage"
    ],
    "daysAgo": 6,
    "featured": false,
    "image": "assets/img/property-9.svg",
    "rentDeposit": 2334000000,
    "rentMonthly": 66600000,
    "price": 66600000
  },
  {
    "id": 22,
    "title": "سوئیت اداری بهشتی",
    "dealType": "sale",
    "propertyType": "office",
    "neighborhood": "بهشتی",
    "city": "لاهیجان",
    "area": 80,
    "bedrooms": 0,
    "parking": 2,
    "amenities": [
      "parking",
      "security"
    ],
    "daysAgo": 25,
    "featured": false,
    "image": "assets/img/property-10.svg",
    "price": 6740000000
  },
  {
    "id": 23,
    "title": "آپارتمان لاکچری بهشتی",
    "dealType": "mortgage",
    "propertyType": "apartment",
    "neighborhood": "بهشتی",
    "city": "لاهیجان",
    "area": 160,
    "bedrooms": 3,
    "parking": 1,
    "amenities": [
      "rooftop",
      "gym",
      "security"
    ],
    "daysAgo": 25,
    "featured": true,
    "image": "assets/img/property-11.svg",
    "price": 7855000000
  },
  {
    "id": 24,
    "title": "زمین کلنگی نیما",
    "dealType": "mortgage",
    "propertyType": "land",
    "neighborhood": "نیما",
    "city": "لاهیجان",
    "area": 220,
    "bedrooms": 0,
    "parking": 0,
    "amenities": [],
    "daysAgo": 1,
    "featured": false,
    "image": "assets/img/property-12.svg",
    "price": 10473000000
  },
  {
    "id": 25,
    "title": "آپارتمان دوبلکس کارگر",
    "dealType": "sale",
    "propertyType": "apartment",
    "neighborhood": "کارگر",
    "city": "لاهیجان",
    "area": 120,
    "bedrooms": 2,
    "parking": 3,
    "amenities": [
      "balcony",
      "pool",
      "gym",
      "storage"
    ],
    "daysAgo": 21,
    "featured": false,
    "image": "assets/img/property-1.svg",
    "price": 14740000000
  },
  {
    "id": 26,
    "title": "آپارتمان نوساز بهشتی",
    "dealType": "rent",
    "propertyType": "apartment",
    "neighborhood": "بهشتی",
    "city": "لاهیجان",
    "area": 140,
    "bedrooms": 3,
    "parking": 0,
    "amenities": [
      "pool",
      "gym"
    ],
    "daysAgo": 6,
    "featured": true,
    "image": "assets/img/property-2.svg",
    "rentDeposit": 1262000000,
    "rentMonthly": 59200000,
    "price": 59200000
  },
  {
    "id": 27,
    "title": "زمین با مجوز ساخت مطهری",
    "dealType": "sale",
    "propertyType": "land",
    "neighborhood": "مطهری",
    "city": "لاهیجان",
    "area": 220,
    "bedrooms": 0,
    "parking": 0,
    "amenities": [],
    "daysAgo": 0,
    "featured": false,
    "image": "assets/img/property-3.svg",
    "price": 29310000000
  },
  {
    "id": 28,
    "title": "آپارتمان بازسازی‌شده خرمشهر",
    "dealType": "sale",
    "propertyType": "apartment",
    "neighborhood": "خرمشهر",
    "city": "لاهیجان",
    "area": 110,
    "bedrooms": 2,
    "parking": 0,
    "amenities": [
      "pool",
      "gym",
      "elevator",
      "storage"
    ],
    "daysAgo": 5,
    "featured": false,
    "image": "assets/img/property-4.svg",
    "price": 9150000000
  },
  {
    "id": 29,
    "title": "آپارتمان لاکچری خرمشهر",
    "dealType": "mortgage",
    "propertyType": "apartment",
    "neighborhood": "خرمشهر",
    "city": "لاهیجان",
    "area": 180,
    "bedrooms": 3,
    "parking": 2,
    "amenities": [
      "balcony",
      "gym",
      "parking"
    ],
    "daysAgo": 14,
    "featured": true,
    "image": "assets/img/property-5.svg",
    "price": 7052000000
  },
  {
    "id": 30,
    "title": "پنت‌هاوس ویو دار رودبنه",
    "dealType": "rent",
    "propertyType": "penthouse",
    "neighborhood": "رودبنه",
    "city": "لاهیجان",
    "area": 350,
    "bedrooms": 4,
    "parking": 1,
    "amenities": [
      "storage",
      "gym",
      "pool",
      "elevator"
    ],
    "daysAgo": 0,
    "featured": false,
    "image": "assets/img/property-6.svg",
    "rentDeposit": 5058000000,
    "rentMonthly": 310000000,
    "price": 310000000
  }
];

const TYPE_LABELS = {
  "villa": "ویلا",
  "apartment": "آپارتمان",
  "penthouse": "پنت‌هاوس",
  "land": "زمین",
  "commercial": "تجاری",
  "office": "اداری"
};
const DEAL_LABELS = {
  "sale": "فروش",
  "rent": "اجاره",
  "mortgage": "رهن کامل"
};
const AMENITY_LABELS = {
  "elevator": "آسانسور",
  "parking": "پارکینگ",
  "storage": "انباری",
  "balcony": "بالکن",
  "security": "نگهبانی",
  "pool": "استخر",
  "gym": "سالن ورزشی",
  "rooftop": "روف‌گاردن"
};
const NEIGHBORHOODS = [
  "مطهری",
  "گلستان",
  "بهشتی",
  "نیما",
  "کوچصفهان",
  "لاکانی",
  "سیاهکل‌روبرو",
  "ساحلی",
  "کارگر",
  "لیل‌آباد",
  "امام خمینی",
  "استخر",
  "چمخاله",
  "رودبنه",
  "کریمی",
  "آستانه‌اشرفیه",
  "دیلمان",
  "خرمشهر"
];
